update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,6 +43,10 @@ jobs:
           - os: macos-latest
             goos: darwin
             goarch: [amd64, arm64]
+          # FreeBSD
+          - os: freebsd-latest
+            goos: freebsd
+            goarch: [amd64, 386, arm, armv6, armv7, armv8, arm64]
 
     steps:
       - uses: actions/checkout@v3
@@ -61,18 +65,33 @@ jobs:
             mingw-w64-x86_64-gcc
             mingw-w64-i686-gcc
 
-      - name: 构建
+      - name: 构建 No sqlite3
+        env:
+          GOOS: ${{ matrix.goos }}
+          CGO_ENABLED: 0
+        run: |
+          for arch in ${{ join(matrix.goarch, ' ') }}; do
+          echo "Building for ${{ matrix.goos }}-${arch}"
+          output_name="sixin-server-${{ matrix.goos }}-${arch}"
+          if [ "${{ matrix.goos }}" = "windows" ]; then
+              output_name+='.exe'
+          fi
+          CGO_ENABLED=0 GOARCH=${arch} go build -v -o ${output_name} || echo "Failed to build for ${arch}"
+          done
+        shell: bash
+
+      - name: 构建 sqlite3
         env:
           GOOS: ${{ matrix.goos }}
           CGO_ENABLED: 1
         run: |
           for arch in ${{ join(matrix.goarch, ' ') }}; do
-            echo "Building for ${{ matrix.goos }}-${arch}"
-            output_name="sixin-server-${{ matrix.goos }}-${arch}"
-            if [ "${{ matrix.goos }}" = "windows" ]; then
+          echo "Building for ${{ matrix.goos }}-${arch}"
+          output_name="sixin-server-${{ matrix.goos }}-${arch}-sqlite3"
+          if [ "${{ matrix.goos }}" = "windows" ]; then
               output_name+='.exe'
-            fi
-            CGO_ENABLED=1 GOARCH=${arch} go build -v -o ${output_name} || echo "Failed to build for ${arch}"
+          fi
+          CGO_ENABLED=1 GOARCH=${arch} go build -v -o ${output_name} || echo "Failed to build for ${arch}"
           done
         shell: bash
 
